### ISSUE TITLE
Only one import list from lidarr is being imported

### ISSUE THREAD

**Issue by Davo1624** [cmathews393/spotify-to-plex#29] opened 2024-07-05 17:14 UTC
**Describe the bug**
I have several spotify lists in lidarr but the script is only syncing one to plex

**To Reproduce**
Run script
Check log
Only shows completion of one playlist.

For example:
2024-07-05 13:09:27.211 | DEBUG    | spotiplex.modules.spotiplex.main:process_playlist:101 - Processed playlist 'Modern Bluegrass'.
This is the only playlist that is created, however I have several more in lidarr

**Expected behavior**
All playlists to be synced

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Unraid 7.0 (running script natively, not docker)

**Comment by Davo1624** [comment] 2024-07-05 17:14
As an aside, when I manually add playlists to config.toml those are also not being processed

**Comment by cmathews393** [comment] 2024-07-05 17:31
Can you confirm that the playlists in Lidarr are all Spotify playlists? And provide the spotiplex.log file (please use pastebin or another service and don't paste here)

**Comment by Davo1624** [comment] 2024-07-05 17:40
Sure thing! Here is the log:
https://privatebin.net/?c66cdec2fed7d58f#6p9WgnmBT4KaxryAFysHgMRWQwJ6dVtXDopuSKvP83FW

Below are screenshots of the playlists in lidarr and the associated playlists in spotify
![image](https://github.com/cmathews393/spotify-to-plex/assets/85573606/5fd44b41-f41b-424d-85a3-c55001505496)

![image](https://github.com/cmathews393/spotify-to-plex/assets/85573606/95e40eb7-54af-47a4-ae81-03c9a9f2fd74)

**Comment by Davo1624** [comment] 2024-07-05 17:41
Messing around a bit, it looks like whatever list is listed first alphabetically in lidarr is the only list that syncs with spotiplex script. I changed one playlist to `Spotify 90s Hip Hop` and that list was synced but not the `Spotify Bluegrass` list

**Comment by cmathews393** [comment] 2024-07-05 17:42
Oh, that helps a lot actually, the issue is that it goes for the first match to Spotify in the Lidarr lists and then uses that. Is there a reason you use multiple import lists in lidarr rather than just one import list for multiple playlists?

**Comment by Davo1624** [comment] 2024-07-05 17:45
In Lidarr I use separate tags for each list, helps me keep track with what artist was added by which list.

**Comment by cmathews393** [comment] 2024-07-05 17:55
Ah yeah that makes sense. Okay, let me think about the best way to fix that. I don't think that was the behavior previously. Can you attach logs for when you do the manual lists as well? That one I'm really not sure about

**Comment by Davo1624** [comment] 2024-07-05 17:58
Maybe I am doing the manual list import, I assumed if I added the list ID in the config it would be synced?

Relevant portion of config:
```
[spotiplex]
lidarr_sync = "true"
plex_users = "davo1624" #COMMA SEPARATED LIST, NO SPACES! user1,user2 NOT user1, user2
worker_count = 4
seconds_interval = 60 #Deprecated, should be replaced with crontab generator
manual_playlists = "6lJ6bBkC4VPGIPf35HgX2C,0pzy4rVhdd5Lpb0ShfrGMz" 
```
and the command I use is ` poetry run spotiplex sync-lidarr-imports`

**Comment by cmathews393** [comment] 2024-07-05 18:09
It should but I might have broken it somehow. I usually use the full link so it's possible I messed something up with the IDs

**Comment by Davo1624** [comment] 2024-07-05 18:16
I tried with the full url as well and the logs never gave any indication it was trying to import them. If my config looks correct I will switch back to full url and try again

**Comment by cmathews393** [comment] 2024-07-05 18:29
Oh, I just looked over your comment again, you need to use sync-manual-lists :)

**Comment by Davo1624** [comment] 2024-07-05 18:39
Oh wow, yeah that worked :D

**Comment by cmathews393** [comment] 2024-07-05 18:41
I'll push a fix for the multiple import lists shortly

**Comment by Davo1624** [comment] 2024-07-05 18:51
That's great!! Many thanks for the quick responses.

Unrelated at all but it looks like a lot of tracks aren't being found because of apostrophes in the track name causing matches to not be found. Not sure if this has been reported before or not, if you  want me to open a separate GHI I'm happy to do so.

**Comment by cmathews393** [comment] 2024-07-05 18:52
Yeah do a separate issue, haven't noticed that but probably a quick fix. Merging the fix for this into main now.

**Closed** 2024-07-05 18:52 UTC
Labels: bug, High Priority, regression

**Comment by Davo1624** [comment] 2024-07-05 21:01
Can confirm this now syncs all lidarr playlists, thanks!!
